var linear_containers_functions =
[
    [ "IotLink_IsLinked", "linear_containers_function_link_islinked.html", null ],
    [ "IotListDouble_Create", "linear_containers_function_list_double_create.html", null ],
    [ "IotListDouble_Count", "linear_containers_function_list_double_count.html", null ],
    [ "IotListDouble_IsEmpty", "linear_containers_function_list_double_isempty.html", null ],
    [ "IotListDouble_PeekHead", "linear_containers_function_list_double_peekhead.html", null ],
    [ "IotListDouble_PeekTail", "linear_containers_function_list_double_peektail.html", null ],
    [ "IotListDouble_InsertHead", "linear_containers_function_list_double_inserthead.html", null ],
    [ "IotListDouble_InsertTail", "linear_containers_function_list_double_inserttail.html", null ],
    [ "IotListDouble_InsertBefore", "linear_containers_function_list_double_insertbefore.html", null ],
    [ "IotListDouble_InsertAfter", "linear_containers_function_list_double_insertafter.html", null ],
    [ "IotListDouble_InsertSorted", "linear_containers_function_list_double_insertsorted.html", null ],
    [ "IotListDouble_Remove", "linear_containers_function_list_double_remove.html", null ],
    [ "IotListDouble_RemoveHead", "linear_containers_function_list_double_removehead.html", null ],
    [ "IotListDouble_RemoveTail", "linear_containers_function_list_double_removetail.html", null ],
    [ "IotListDouble_RemoveAll", "linear_containers_function_list_double_removeall.html", null ],
    [ "IotListDouble_FindFirstMatch", "linear_containers_function_list_double_findfirstmatch.html", null ],
    [ "IotListDouble_RemoveFirstMatch", "linear_containers_function_list_double_removefirstmatch.html", null ],
    [ "IotListDouble_RemoveAllMatches", "linear_containers_function_list_double_removeallmatches.html", null ],
    [ "IotDeQueue_Create", "linear_containers_function_queue_create.html", null ],
    [ "IotDeQueue_Count", "linear_containers_function_queue_count.html", null ],
    [ "IotDeQueue_IsEmpty", "linear_containers_function_queue_isempty.html", null ],
    [ "IotDeQueue_PeekHead", "linear_containers_function_queue_peekhead.html", null ],
    [ "IotDeQueue_PeekTail", "linear_containers_function_queue_peektail.html", null ],
    [ "IotDeQueue_EnqueueHead", "linear_containers_function_queue_enqueuehead.html", null ],
    [ "IotDeQueue_DequeueHead", "linear_containers_function_queue_dequeuehead.html", null ],
    [ "IotDeQueue_EnqueueTail", "linear_containers_function_queue_enqueuetail.html", null ],
    [ "IotDeQueue_DequeueTail", "linear_containers_function_queue_dequeuetail.html", null ],
    [ "IotDeQueue_Remove", "linear_containers_function_queue_remove.html", null ],
    [ "IotDeQueue_RemoveAll", "linear_containers_function_queue_removeall.html", null ],
    [ "IotDeQueue_RemoveAllMatches", "linear_containers_function_queue_removeallmatches.html", null ]
];