
SIMPLELINK_CC32XX_SDK_INSTALL_DIR ?= $(abspath ../../../../../../..)

include $(SIMPLELINK_CC32XX_SDK_INSTALL_DIR)/imports.mak

ROOT=$(SIMPLELINK_CC32XX_SDK_INSTALL_DIR)/source/ti/devices/cc32xx

#
# Source path
#
VPATH = $(ROOT)/driverlib

CC = "$(GCC_ARMCOMPILER)/bin/arm-none-eabi-gcc"
AR = "$(GCC_ARMCOMPILER)/bin/arm-none-eabi-ar"

STDINC = "$(GCC_ARMCOMPILER)/include"

#
# Include path
#
IPATH  = -I$(ROOT)/
IPATH += -I$(ROOT)/driverlib
IPATH += -I$(ROOT)/inc
ifdef COM_TI_SIMPLELINK_MSP432_SDK_INSTALL_DIR
IPATH += -I$(COM_TI_SIMPLELINK_MSP432_SDK_INSTALL_DIR)/source
endif
IPATH += -I$(STDINC)

CFLAGS = -Dgcc -mcpu=cortex-m4 -mthumb -ffunction-sections -fdata-sections -MD -std=c99 -g -O0 -c
CFLAGS += $(IPATH)

ifdef COM_TI_SIMPLELINK_MSP432_SDK_INSTALL_DIR
CFLAGS += -mfloat-abi=hard
else
CFLAGS += -mfloat-abi=soft
endif

CFILES = \
    adc.c \
    aes.c \
    camera.c \
    cpu.c \
    crc.c \
    des.c \
    flash.c \
    gpio.c \
    hwspinlock.c \
    i2c.c \
    interrupt.c \
    i2s.c \
    pin.c \
    prcm.c \
    sdhost.c \
    shamd5.c \
    spi.c \
    systick.c \
    timer.c \
    uart.c \
    udma.c \
    utils.c \
    wdt.c


OBJCFILES = $(CFILES:.c=.obj)

driverlib.a: $(OBJCFILES)
	@ echo ar $@ ...
	@ $(RM) $@ > $(DEVNULL) 2>&1
	@ $(AR) -cr $@ $(OBJCFILES)

%.obj:%.c
	@ echo cc $@ ...
	@ $(CC) $(CFLAGS) $< -o $@

clean:
	@ echo cleaning ...
	@ $(RM) *.obj > $(DEVNULL) 2>&1
	@ $(RM) *.a > $(DEVNULL) 2>&1
