
:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :ignore_arg
    - :expect_any_args
    - :array
    - :callback
    - :return_thru_ptr
  :callback_include_count: true # include a count arg when calling the callback
  :callback_after_arg_check: false # check arguments before calling the callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
    CK_ULONG_PTR: UINT32*
  :includes:        # This will add these includes to each mock.
    - <stdbool.h>
    - <stdint.h>
    - <fcntl.h>
  :treat_externs: :exclude  # Now the extern-ed functions will be mocked.
  :weak: __attribute__((weak))
  :verbosity: 3
  :attributes:
    - PRIVILEGED_FUNCTION
    - MBEDTLS_DEPRECATED
    - 'int fcntl(int s, int cmd, ...);'
  :strippables:
    - PRIVILEGED_FUNCTION
    - portDONT_DISCARD
    - MBEDTLS_DEPRECATED
    - '(?:fcntl\s*\(+.*?\)+)' # this function is causing some trouble with code coverage as the annotations are calling the mocked one, so we won't mock it
    - '(?:vQueueUnregisterQueue\s*\(+.*?\)+)' # this function is causing some trouble with code coverage as the annotations are calling the mocked one, so we won't mock it
    - '(?:pcQueueGetName\s*\(+.*?\)+)' # this function is causing some trouble with code coverage as the annotations are calling the mocked one, so we won't mock it
    - '(?:vQueueAddToRegistry\s*\(+.*?\)+)' # this function is causing some trouble with code coverage as the annotations are calling the mocked one, so we won't mock it
  :treat_externs: :include
  :includes_c_pre_header:
    - "portableDefs.h"
  :includes_h_pre_orig_header:
    - "portableDefs.h"
  :includes_c_pre_header:
    - "iot_pkcs11.h" # For iot_pkcs11_pal.h
    - "md_internal.h"
    - "pk_internal.h"
  :includes:
    - "portableDefs.h"
    - "projdefs.h"
    - "task.h"
