AMAZON_FREERTOS_LIB_DIR := $(AMAZON_FREERTOS_PATH)/lib
AMAZON_FREERTOS_DEMOS_DIR := $(AMAZON_FREERTOS_PATH)/demos

COMPONENT_EXTRA_INCLUDES := $(AMAZON_FREERTOS_LIB_DIR)/third_party/pkcs11 $(AMAZON_FREERTOS_LIB_DIR)/ota/portable/espressif/esp32_devkitc_esp_wrover_kit
