# The smoke stage checks that a few things are mostly working to avoid wasting
# a lot of runner time when there is an obvious problem.
stages:
  - smoke
  - test
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CY_DEP_DIR: $CI_PROJECT_DIR/cydep

###############################################################################
#############################        TEST        ##############################
###############################################################################

test_afr-CY8CKIT_062_WIFI_BT:
  stage: smoke
  tags:
    - devops-linux
  script:
    - bash cypress_internal_test/test_afr.sh CY8CKIT_062_WIFI_BT GCC_ARM

test_afr-CY8CKIT-064S0S2-4343W:
  stage: smoke
  tags:
    - devops-linux
    - U18.04
  script:
    - bash cypress_internal_test/test_afr_cysecure.sh ubuntu CY8CKIT_064S0S2_4343W GCC_ARM --no-cmake
  allow_failure: true

test_afr-CY8CPROTO_062_4343W:
  stage: test
  tags:
    - devops-linux
  script:
    - bash cypress_internal_test/test_afr.sh CY8CPROTO_062_4343W GCC_ARM

test_afr-CY8CKIT_062S2_43012:
  stage: test
  tags:
    - devops-linux
  script:
    - bash cypress_internal_test/test_afr.sh CY8CKIT_062S2_43012 GCC_ARM

test_afr-CY8CKIT_064S0S2_4343W:
  stage: smoke
  tags:
    - devops-linux
    - U18.04
  script:
    - bash cypress_internal_test/test_afr_cysecure.sh ubuntu CY8CKIT_064S0S2_4343W GCC_ARM --no-p6make
  allow_failure: true
  artifacts:
    expire_in: 1 day
    paths:
      - build/cmake/aws_demos.tgz

test_afr-ARM:
  stage: test
  tags:
    - devops-linux
  script:
    - bash cypress_internal_test/test_afr.sh CY8CPROTO_062_4343W ARM --no-p6make

# Currently does not compile successfully with psoc6make
test_afr-ARM-p6make:
  stage: test
  tags:
    - devops-linux
  script:
    - bash cypress_internal_test/test_afr.sh CY8CPROTO_062_4343W ARM --no-cmake
  allow_failure: true

test_afr-IAR:
  stage: test
  tags:
    - devops-win
    #- IAR_8.32.1
    - IAR_8.50.4
  script:
    - bash cypress_internal_test/test_afr.sh CY8CPROTO_062_4343W IAR --no-p6make

# Currently does not compile successfully with psoc6make
test_afr-IAR-p6make:
  stage: test
  tags:
    - devops-win
    #- IAR_8.32.1
    - IAR_8.50.4
  script:
    - bash cypress_internal_test/test_afr.sh CY8CPROTO_062_4343W IAR --no-cmake

test_cmake:
  stage: smoke
  tags:
    - devops-linux
  script:
    - bash cypress_internal_test/cmake-test/comp_test.sh
    - bash cypress_internal_test/cmake-test/ignore_test.sh
    - bash cypress_internal_test/cmake-test/include_test.sh
    - bash cypress_internal_test/cmake-test/file_type_test.sh

# Run coverity static analysis test
test_coverity_CY8CPROTO_062_4343W:
  stage: test
  tags:
    - devops-linux
  variables:
    CY_DEP_DIR: $CI_PROJECT_DIR/cydep
  script:
    - bash cypress_internal_test/coverity/coverity_report_ubuntu.sh CY8CPROTO_062_4343W ubuntu
  allow_failure: true
  artifacts:
    paths:
      - cov-analyze-errorlist-afr_ota_CY8CPROTO_062_4343W.txt

test_coverity_CY8CKIT_064S0S2_4343W:
  stage: test
  tags:
    - devops-linux
  variables:
    CY_DEP_DIR: $CI_PROJECT_DIR/cydep
  script:
    - bash cypress_internal_test/coverity/coverity_report_ubuntu.sh CY8CKIT_064S0S2_4343W ubuntu
  allow_failure: true
  artifacts:
    paths:
      - cov-analyze-errorlist-afr_ota_CY8CKIT_064S0S2_4343W.txt

test_afr-check_board_sync:
  stage: test
  tags:
    - devops-linux
  script:
    - bash cypress_internal_test/board_sync/check_board_sync.sh

###############################################################################
#####################  Amazon-FREERtos device tester tests  ###################
###############################################################################

# Run AFR Device tester when $AFR_DEVICE_TESTER is specified
afr_device_tester_auto_CY8CPROTO-062-4343W:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CPROTO-062-4343W
  only:
    variables:
      - $AFR_DEVICE_TESTER
      - $AFR_TEST_CY8CPROTO_062_4343W
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - python3.7 cypress_internal_test/device_tester/run_test.py CY8CPROTO_062_4343W arm-gcc '3.1.0' 'OTA_NO' $TEST_ARGS
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - cypress_internal_test/device_tester/test_results

# Run AFR Device tester when $AFR_DEVICE_TESTER is specified
afr_device_tester_auto_CY8CKIT-062-WIFI-BT:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CKIT-062-WIFI-BT
  only:
    variables:
      - $AFR_DEVICE_TESTER
      - $AFR_TEST_CY8CKIT_062_WIFI_BT
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - python3.7 cypress_internal_test/device_tester/run_test.py CY8CKIT_062_WIFI_BT arm-gcc '3.1.0' 'OTA_NO' $TEST_ARGS
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - cypress_internal_test/device_tester/test_results

# Run AFR Device tester when $AFR_DEVICE_TESTER is specified
afr_device_tester_auto_CY8CKIT-062S2-43012:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CKIT-062S2-43012
  only:
    variables:
      - $AFR_DEVICE_TESTER
      - $AFR_TEST_CY8CKIT_062S2_43012
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - python3.7 cypress_internal_test/device_tester/run_test.py CY8CKIT_062S2_43012 arm-gcc '3.1.0' 'OTA_NO' $TEST_ARGS
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - cypress_internal_test/device_tester/test_results

# Run AFR Device tester when $AFR_DEVICE_TESTER is specified
afr_device_tester_auto_CY8CKIT-064S0S2-4343W:
  stage: test
  tags:
    - tfm-idt-afr
  only:
    variables:
      - $AFR_DEVICE_TESTER_064S0S2
  before_script:
    - source cypress_internal_test/set_idt_env.sh
    - setup_idt
  script:
    # NOTE the board name below use '_' instead of '-'
    - python3.7 cypress_internal_test/device_tester/run_test.py CY8CKIT_064S0S2_4343W arm-gcc '3.1.0' 'OTA_NO' $TEST_ARGS
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - cypress_internal_test/device_tester/test_results
  resource_group: afr_test
  allow_failure: true
      
# Run AFR Device tester when AFR_TEST_OTA_CY8CKIT_064S0S2_4343W is specified
afr_device_tester_auto_CY8CKIT-064S0S2-4343W_OTA:
  stage: test
  tags:
    - tfm-idt-afr
  only:
    variables:
      - $AFR_TEST_OTA_CY8CKIT_064S0S2_4343W
  before_script:
    - source cypress_internal_test/set_idt_env.sh
    - setup_idt
  script:
    # NOTE the board name below use '_' instead of '-'
    # Enable OTA parameter should be: OTA_NO or OTA_YES
    - python3.7 cypress_internal_test/device_tester/run_test.py CY8CKIT_064S0S2_4343W arm-gcc '3.1.0' 'OTA_YES' $TEST_ARGS
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - cypress_internal_test/device_tester/test_results
  resource_group: afr_test
  allow_failure: true

# Run AFR Device tester when $AFR_DEVICE_TESTER and AFR_DEVICE_OTA is specified
afr_device_tester_auto_CY8CPROTO-062-4343W_OTA:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CPROTO-062-4343W
  only:
    variables:
      - $AFR_DEVICE_OTA
      - $AFR_TEST_OTA_CY8CPROTO_062_4343W
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - python3 cypress_internal_test/device_tester/run_test.py CY8CPROTO_062_4343W arm-gcc '3.1.0' 'OTA_YES' $TEST_ARGS
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - cypress_internal_test/device_tester/test_results

# Run AFR Device tester when $AFR_DEVICE_TESTER and AFR_DEVICE_OTA is specified
afr_device_tester_auto_CY8CKIT-062-WIFI-BT_OTA:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CKIT-062-WIFI-BT
  only:
    variables:
      - $AFR_DEVICE_OTA
      - $AFR_TEST_OTA_CY8CKIT_062_WIFI_BT
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - python3 cypress_internal_test/device_tester/run_test.py CY8CKIT_062_WIFI_BT arm-gcc '3.1.0' 'OTA_YES' $TEST_ARGS
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - cypress_internal_test/device_tester/test_results

# Run AFR Device tester when $AFR_DEVICE_TESTER and AFR_DEVICE_OTA is specified
afr_device_tester_auto_CY8CKIT-062S2-43012_OTA:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CKIT-062S2-43012
  only:
    variables:
      - $AFR_DEVICE_OTA
      - $AFR_TEST_OTA_CY8CKIT_062S2_43012
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - python3 cypress_internal_test/device_tester/run_test.py CY8CKIT_062S2_43012 arm-gcc '3.1.0' 'OTA_YES' $TEST_ARGS
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - cypress_internal_test/device_tester/test_results

###############################################################################
############################  Amazon-FREERtos demo tests  #####################
###############################################################################

# Run AFR demo test when $AFR_DEMO_TEST is specified
afr_demo_test_auto_CY8CPROTO-062-4343W:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CPROTO-062-4343W
  only:
    variables:
      - $AFR_DEMO_TEST
      - $AFR_TEST_CY8CPROTO_062_4343W
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - bash cypress_internal_test/demo_test/run_test.sh CY8CPROTO_062_4343W

# Run AFR demo test when $AFR_DEMO_TEST is specified
afr_demo_test_auto_CY8CKIT-062-WIFI-BT:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CKIT-062-WIFI-BT
  only:
    variables:
      - $AFR_DEMO_TEST
      - $AFR_TEST_CY8CKIT_062_WIFI_BT
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - bash cypress_internal_test/demo_test/run_test.sh CY8CKIT_062_WIFI_BT

# Run AFR demo test when $AFR_DEMO_TEST is specified
afr_demo_test_auto_CY8CKIT-062S2-43012:
  stage: test
  tags:
    - bsp_csp_afr
    - device-tester
    - CY8CKIT-062S2-43012
  only:
    variables:
      - $AFR_DEMO_TEST
      - $AFR_TEST_CY8CKIT_062S2_43012
  script:
    # NOTE the board name below use '_' instead of '-'
    - source /home/tester/venv/afr/bin/activate
    - bash cypress_internal_test/demo_test/run_test.sh CY8CKIT_062S2_43012

# Run AFR Device tester when $AFR_DEMO_TEST_CY8CKIT_064S0S2_4343W_GCC is specified
afr_demo_test_auto_CY8CKIT_064S0S2_4343W_GCC:
  stage: test
  tags:
    - tfm-idt-afr
  only:
    variables:
      - $AFR_DEMO_TEST_CY8CKIT_064S0S2_4343W_GCC
  script:
    # NOTE the board name below use '_' instead of '-'
    - bash -e cypress_internal_test/demo_test/run_test_secure.sh  CY8CKIT_064S0S2_4343W GCC_ARM $deviceID
  resource_group: afr_test

# Run AFR Device tester when $AFR_DEMO_TEST_CY8CKIT_064S0S2_4343W_ARM is specified
afr_demo_test_auto_CY8CKIT_064S0S2_4343W_ARM:
  stage: test
  tags:
    - tfm-idt-afr
  only:
    variables:
      - $AFR_DEMO_TEST_CY8CKIT_064S0S2_4343W_ARM
  script:
    # NOTE the board name below use '_' instead of '-'
    - bash -e cypress_internal_test/demo_test/run_test_secure.sh  CY8CKIT_064S0S2_4343W ARM $deviceID
  resource_group: afr_test
  
# Run AFR Device tester when $AFR_JITP_TEST_CY8CKIT_064S0S2_4343W_GCC is specified
.afr_jitp_test_auto_CY8CKIT_064S0S2_4343W_GCC:
  stage: test
  tags:
    - tfm-idt-afr
  only:
    variables:
      - $AFR_JITP_TEST_CY8CKIT_064S0S2_4343W_GCC
  script:
    # NOTE the board name below use '_' instead of '-'
    - bash -e cypress_internal_test/demo_test/run_test_jitp.sh  CY8CKIT_064S0S2_4343W GCC_ARM $deviceID
  resource_group: afr_test
  
# Run AFR Device tester when $AFR_JITP_TEST_CY8CKIT_064S0S2_4343W_GCC is specified
afr_jitp_test_auto_CY8CKIT_064S0S2_4343W_ARM:
  stage: test
  tags:
    - tfm-idt-afr
  only:
    variables:
      - $AFR_JITP_TEST_CY8CKIT_064S0S2_4343W_ARM
  script:
    # NOTE the board name below use '_' instead of '-'
    - bash -e cypress_internal_test/demo_test/run_test_jitp.sh  CY8CKIT_064S0S2_4343W ARM $deviceID
  resource_group: afr_test
 
###############################################################################
############################  Amazon-FREERtos demo build tests  ###############
###############################################################################
 

    
test_afr_build-CY8CKIT-064S0S2-4343W-WIN:
  stage: test
  tags:
    - devops-win
    - IAR_8.50.4
  script:
    - bash -e cypress_internal_test/demo_test/run_test_build.sh win CY8CKIT_064S0S2_4343W
    
test_afr_build-CY8CKIT-064S0S2-4343W-MAC:
  stage: test
  tags:
    - devops-mac
  script:
    - bash -e cypress_internal_test/demo_test/run_test_build.sh mac CY8CKIT_064S0S2_4343W
    
test_afr_build-CY8CKIT-064S0S2-4343W-LIN:
  stage: test
  tags:
    - devops-linux
  script:
    - bash -e cypress_internal_test/demo_test/run_test_build.sh ubuntu CY8CKIT_064S0S2_4343W
 
.afr_jitp_test_build_CY8CKIT_064S0S2_4343W_WIN:
  stage: smoke
  tags:
    - devops-win
    - IAR_8.50.4
  script:
    - bash -e cypress_internal_test/demo_test/run_test_jitp_build.sh win CY8CKIT_064S0S2_4343W 

.afr_jitp_test_build_CY8CKIT_064S0S2_4343W_LIN:
  stage: test
  tags:
    - devops-linux
  script:
    - bash -e cypress_internal_test/demo_test/run_test_jitp_build.sh ubuntu CY8CKIT_064S0S2_4343W 
    
.afr_jitp_test_build_CY8CKIT_064S0S2_4343W_MAC:
  stage: test
  tags:
    - devops-mac
  script:
    - bash -e cypress_internal_test/demo_test/run_test_jitp_build.sh mac CY8CKIT_064S0S2_4343W
