/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No 
* other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all 
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM 
* EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES 
* SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS 
* SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of 
* this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2018 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/
/***********************************************************************************************************************
* File Name    : mcu_mapped_interrupts.c
* Description  : This module maps Interrupt A interrupts. Which interrupts are mapped depends on the macros in
*                r_bsp_interrupt_config.h.
***********************************************************************************************************************/
/**********************************************************************************************************************
* History : DD.MM.YYYY Version   Description
*         : 27.07.2018 1.00      First Release
*         : 28.02.2019 1.01      Fixed coding style.
***********************************************************************************************************************/

/***********************************************************************************************************************
Macro definitions
***********************************************************************************************************************/
/* Multiple inclusion prevention macro */
#ifndef MCU_MAPPED_INTERRUPTS_H
#define MCU_MAPPED_INTERRUPTS_H

/* The following macros define the number for each interrupt request source as it pertains to being an Interrupt A
 * interrupt. These values are used when setting the interrupt select registers (i.e. SLIARn).
 */
/* Available Interrupt A Sources. */
#define BSP_PRV_INT_A_NUM_MTU0_TGIA0                                      1
#define BSP_PRV_INT_A_NUM_MTU0_TGIB0                                      2
#define BSP_PRV_INT_A_NUM_MTU0_TGIC0                                      3
#define BSP_PRV_INT_A_NUM_MTU0_TGID0                                      4
#define BSP_PRV_INT_A_NUM_MTU0_TCIV0                                      5
#define BSP_PRV_INT_A_NUM_MTU0_TGIE0                                      6
#define BSP_PRV_INT_A_NUM_MTU0_TGIF0                                      7
#define BSP_PRV_INT_A_NUM_MTU1_TGIA1                                      8
#define BSP_PRV_INT_A_NUM_MTU1_TGIB1                                      9
#define BSP_PRV_INT_A_NUM_MTU1_TCIV1                                      10
#define BSP_PRV_INT_A_NUM_MTU1_TCIU1                                      11
#define BSP_PRV_INT_A_NUM_MTU2_TGIA2                                      12
#define BSP_PRV_INT_A_NUM_MTU2_TGIB2                                      13
#define BSP_PRV_INT_A_NUM_MTU2_TCIV2                                      14
#define BSP_PRV_INT_A_NUM_MTU2_TCIU2                                      15
#define BSP_PRV_INT_A_NUM_MTU3_TGIA3                                      16
#define BSP_PRV_INT_A_NUM_MTU3_TGIB3                                      17
#define BSP_PRV_INT_A_NUM_MTU3_TGIC3                                      18
#define BSP_PRV_INT_A_NUM_MTU3_TGID3                                      19
#define BSP_PRV_INT_A_NUM_MTU3_TCIV3                                      20
#define BSP_PRV_INT_A_NUM_MTU4_TGIA4                                      21
#define BSP_PRV_INT_A_NUM_MTU4_TGIB4                                      22
#define BSP_PRV_INT_A_NUM_MTU4_TGIC4                                      23
#define BSP_PRV_INT_A_NUM_MTU4_TGID4                                      24
#define BSP_PRV_INT_A_NUM_MTU4_TCIV4                                      25
#define BSP_PRV_INT_A_NUM_MTU5_TGIU5                                      27
#define BSP_PRV_INT_A_NUM_MTU5_TGIV5                                      28
#define BSP_PRV_INT_A_NUM_MTU5_TGIW5                                      29
#define BSP_PRV_INT_A_NUM_MTU6_TGIA6                                      30
#define BSP_PRV_INT_A_NUM_MTU6_TGIB6                                      31
#define BSP_PRV_INT_A_NUM_MTU6_TGIC6                                      32
#define BSP_PRV_INT_A_NUM_MTU6_TGID6                                      33
#define BSP_PRV_INT_A_NUM_MTU6_TCIV6                                      34
#define BSP_PRV_INT_A_NUM_MTU7_TGIA7                                      35
#define BSP_PRV_INT_A_NUM_MTU7_TGIB7                                      36
#define BSP_PRV_INT_A_NUM_MTU7_TGIC7                                      37
#define BSP_PRV_INT_A_NUM_MTU7_TGID7                                      38
#define BSP_PRV_INT_A_NUM_MTU7_TCIV7                                      39
#define BSP_PRV_INT_A_NUM_MTU9_TGIA9                                      47
#define BSP_PRV_INT_A_NUM_MTU9_TGIB9                                      48
#define BSP_PRV_INT_A_NUM_MTU9_TGIC9                                      49
#define BSP_PRV_INT_A_NUM_MTU9_TGID9                                      50
#define BSP_PRV_INT_A_NUM_MTU9_TCIV9                                      51
#define BSP_PRV_INT_A_NUM_MTU9_TGIE9                                      52
#define BSP_PRV_INT_A_NUM_MTU9_TGIF9                                      53
#define BSP_PRV_INT_A_NUM_GPTW0_GTCIA0                                    56
#define BSP_PRV_INT_A_NUM_GPTW0_GTCIB0                                    57
#define BSP_PRV_INT_A_NUM_GPTW0_GTCIC0                                    58
#define BSP_PRV_INT_A_NUM_GPTW0_GTCID0                                    59
#define BSP_PRV_INT_A_NUM_GPTW0_GDTE0                                     60
#define BSP_PRV_INT_A_NUM_GPTW0_GTCIE0                                    61
#define BSP_PRV_INT_A_NUM_GPTW0_GTCIF0                                    62
#define BSP_PRV_INT_A_NUM_GPTW0_GTCIV0                                    63
#define BSP_PRV_INT_A_NUM_GPTW0_GTCIU0                                    64
#define BSP_PRV_INT_A_NUM_GPTW1_GTCIA1                                    65
#define BSP_PRV_INT_A_NUM_GPTW1_GTCIB1                                    66
#define BSP_PRV_INT_A_NUM_GPTW1_GTCIC1                                    67
#define BSP_PRV_INT_A_NUM_GPTW1_GTCID1                                    68
#define BSP_PRV_INT_A_NUM_GPTW1_GDTE1                                     69
#define BSP_PRV_INT_A_NUM_GPTW1_GTCIE1                                    70
#define BSP_PRV_INT_A_NUM_GPTW1_GTCIF1                                    71
#define BSP_PRV_INT_A_NUM_GPTW1_GTCIV1                                    72
#define BSP_PRV_INT_A_NUM_GPTW1_GTCIU1                                    73
#define BSP_PRV_INT_A_NUM_GPTW2_GTCIA2                                    74
#define BSP_PRV_INT_A_NUM_GPTW2_GTCIB2                                    75
#define BSP_PRV_INT_A_NUM_GPTW2_GTCIC2                                    76
#define BSP_PRV_INT_A_NUM_GPTW2_GTCID2                                    77
#define BSP_PRV_INT_A_NUM_GPTW2_GDTE2                                     78
#define BSP_PRV_INT_A_NUM_GPTW2_GTCIE2                                    79
#define BSP_PRV_INT_A_NUM_GPTW2_GTCIF2                                    80
#define BSP_PRV_INT_A_NUM_GPTW2_GTCIV2                                    81
#define BSP_PRV_INT_A_NUM_GPTW2_GTCIU2                                    82
#define BSP_PRV_INT_A_NUM_GPTW3_GTCIA3                                    83
#define BSP_PRV_INT_A_NUM_GPTW3_GTCIB3                                    84
#define BSP_PRV_INT_A_NUM_GPTW3_GTCIC3                                    85
#define BSP_PRV_INT_A_NUM_GPTW3_GTCID3                                    86
#define BSP_PRV_INT_A_NUM_GPTW3_GDTE3                                     87
#define BSP_PRV_INT_A_NUM_GPTW3_GTCIE3                                    88
#define BSP_PRV_INT_A_NUM_GPTW3_GTCIF3                                    89
#define BSP_PRV_INT_A_NUM_GPTW3_GTCIV3                                    90
#define BSP_PRV_INT_A_NUM_GPTW3_GTCIU3                                    91
#define BSP_PRV_INT_A_NUM_GPTW4_GTCIA4                                    92
#define BSP_PRV_INT_A_NUM_GPTW4_GTCIB4                                    93
#define BSP_PRV_INT_A_NUM_GPTW4_GTCIC4                                    94
#define BSP_PRV_INT_A_NUM_GPTW4_GTCID4                                    95
#define BSP_PRV_INT_A_NUM_GPTW4_GDTE4                                     96
#define BSP_PRV_INT_A_NUM_GPTW4_GTCIE4                                    97
#define BSP_PRV_INT_A_NUM_GPTW4_GTCIF4                                    98
#define BSP_PRV_INT_A_NUM_GPTW4_GTCIV4                                    99
#define BSP_PRV_INT_A_NUM_GPTW4_GTCIU4                                   100
#define BSP_PRV_INT_A_NUM_GPTW5_GTCIA5                                   101
#define BSP_PRV_INT_A_NUM_GPTW5_GTCIB5                                   102
#define BSP_PRV_INT_A_NUM_GPTW5_GTCIC5                                   103
#define BSP_PRV_INT_A_NUM_GPTW5_GTCID5                                   104
#define BSP_PRV_INT_A_NUM_GPTW5_GDTE5                                    105
#define BSP_PRV_INT_A_NUM_GPTW5_GTCIE5                                   106
#define BSP_PRV_INT_A_NUM_GPTW5_GTCIF5                                   107
#define BSP_PRV_INT_A_NUM_GPTW5_GTCIV5                                   108
#define BSP_PRV_INT_A_NUM_GPTW5_GTCIU5                                   109
#define BSP_PRV_INT_A_NUM_GPTW6_GTCIA6                                   110
#define BSP_PRV_INT_A_NUM_GPTW6_GTCIB6                                   111
#define BSP_PRV_INT_A_NUM_GPTW6_GTCIC6                                   112
#define BSP_PRV_INT_A_NUM_GPTW6_GTCID6                                   113
#define BSP_PRV_INT_A_NUM_GPTW6_GDTE6                                    114
#define BSP_PRV_INT_A_NUM_GPTW6_GTCIE6                                   115
#define BSP_PRV_INT_A_NUM_GPTW6_GTCIF6                                   116
#define BSP_PRV_INT_A_NUM_GPTW6_GTCIV6                                   117
#define BSP_PRV_INT_A_NUM_GPTW6_GTCIU6                                   118
#define BSP_PRV_INT_A_NUM_GPTW7_GTCIA7                                   119
#define BSP_PRV_INT_A_NUM_GPTW7_GTCIB7                                   120
#define BSP_PRV_INT_A_NUM_GPTW7_GTCIC7                                   121
#define BSP_PRV_INT_A_NUM_GPTW7_GTCID7                                   122
#define BSP_PRV_INT_A_NUM_GPTW7_GDTE7                                    123
#define BSP_PRV_INT_A_NUM_GPTW7_GTCIE7                                   124
#define BSP_PRV_INT_A_NUM_GPTW7_GTCIF7                                   125
#define BSP_PRV_INT_A_NUM_GPTW7_GTCIV7                                   126
#define BSP_PRV_INT_A_NUM_GPTW7_GTCIU7                                   127
#define BSP_PRV_INT_A_NUM_GPTW8_GTCIA8                                   128
#define BSP_PRV_INT_A_NUM_GPTW8_GTCIB8                                   129
#define BSP_PRV_INT_A_NUM_GPTW8_GTCIC8                                   130
#define BSP_PRV_INT_A_NUM_GPTW8_GTCID8                                   131
#define BSP_PRV_INT_A_NUM_GPTW8_GDTE8                                    132
#define BSP_PRV_INT_A_NUM_GPTW8_GTCIE8                                   133
#define BSP_PRV_INT_A_NUM_GPTW8_GTCIF8                                   134
#define BSP_PRV_INT_A_NUM_GPTW8_GTCIV8                                   135
#define BSP_PRV_INT_A_NUM_GPTW8_GTCIU8                                   136
#define BSP_PRV_INT_A_NUM_GPTW9_GTCIA9                                   137
#define BSP_PRV_INT_A_NUM_GPTW9_GTCIB9                                   138
#define BSP_PRV_INT_A_NUM_GPTW9_GTCIC9                                   139
#define BSP_PRV_INT_A_NUM_GPTW9_GTCID9                                   140
#define BSP_PRV_INT_A_NUM_GPTW9_GDTE9                                    141
#define BSP_PRV_INT_A_NUM_GPTW9_GTCIE9                                   142
#define BSP_PRV_INT_A_NUM_GPTW9_GTCIF9                                   143
#define BSP_PRV_INT_A_NUM_GPTW9_GTCIV9                                   144
#define BSP_PRV_INT_A_NUM_GPTW9_GTCIU9                                   145


/* The appropriate macros will now be defined based on the vector selections made by the user.
 * These are the same macros that are defined for constant-mapped interrupts (vectors 0-127). This means that the
 * code can define, setup, and use mapped interrupts the same as would be done for constant-mapped interrupts.
 */
#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIA1)
#define IR_MTU1_TGIA1        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIA1)
#define DTCE_MTU1_TGIA1      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIA1)
#define IER_MTU1_TGIA1       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIA1)
#define IPR_MTU1_TGIA1       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIA1)
#define IEN_MTU1_TGIA1       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIA1)
#define VECT_MTU1_TGIA1      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIA1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIA0)
#define IR_MTU0_TGIA0        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIA0)
#define DTCE_MTU0_TGIA0      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIA0)
#define IER_MTU0_TGIA0       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIA0)
#define IPR_MTU0_TGIA0       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIA0)
#define IEN_MTU0_TGIA0       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIA0)
#define VECT_MTU0_TGIA0      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIA0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIB0)
#define IR_MTU0_TGIB0        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIB0)
#define DTCE_MTU0_TGIB0      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIB0)
#define IER_MTU0_TGIB0       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIB0)
#define IPR_MTU0_TGIB0       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIB0)
#define IEN_MTU0_TGIB0       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIB0)
#define VECT_MTU0_TGIB0      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIB0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIC0)
#define IR_MTU0_TGIC0        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIC0)
#define DTCE_MTU0_TGIC0      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIC0)
#define IER_MTU0_TGIC0       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIC0)
#define IPR_MTU0_TGIC0       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIC0)
#define IEN_MTU0_TGIC0       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIC0)
#define VECT_MTU0_TGIC0      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIC0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGID0)
#define IR_MTU0_TGID0        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGID0)
#define DTCE_MTU0_TGID0      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGID0)
#define IER_MTU0_TGID0       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGID0)
#define IPR_MTU0_TGID0       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGID0)
#define IEN_MTU0_TGID0       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGID0)
#define VECT_MTU0_TGID0      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGID0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TCIV0)
#define IR_MTU0_TCIV0        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TCIV0)
#define DTCE_MTU0_TCIV0      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TCIV0)
#define IER_MTU0_TCIV0       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TCIV0)
#define IPR_MTU0_TCIV0       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TCIV0)
#define IEN_MTU0_TCIV0       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TCIV0)
#define VECT_MTU0_TCIV0      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TCIV0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIE0)
#define IR_MTU0_TGIE0        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIE0)
#define DTCE_MTU0_TGIE0      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIE0)
#define IER_MTU0_TGIE0       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIE0)
#define IPR_MTU0_TGIE0       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIE0)
#define IEN_MTU0_TGIE0       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIE0)
#define VECT_MTU0_TGIE0      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIE0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIF0)
#define IR_MTU0_TGIF0        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIF0)
#define DTCE_MTU0_TGIF0      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIF0)
#define IER_MTU0_TGIF0       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIF0)
#define IPR_MTU0_TGIF0       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIF0)
#define IEN_MTU0_TGIF0       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIF0)
#define VECT_MTU0_TGIF0      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU0_TGIF0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIB1)
#define IR_MTU1_TGIB1        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIB1)
#define DTCE_MTU1_TGIB1      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIB1)
#define IER_MTU1_TGIB1       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIB1)
#define IPR_MTU1_TGIB1       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIB1)
#define IEN_MTU1_TGIB1       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIB1)
#define VECT_MTU1_TGIB1      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TGIB1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIV1)
#define IR_MTU1_TCIV1        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIV1)
#define DTCE_MTU1_TCIV1      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIV1)
#define IER_MTU1_TCIV1       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIV1)
#define IPR_MTU1_TCIV1       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIV1)
#define IEN_MTU1_TCIV1       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIV1)
#define VECT_MTU1_TCIV1      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIV1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIU1)
#define IR_MTU1_TCIU1        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIU1)
#define DTCE_MTU1_TCIU1      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIU1)
#define IER_MTU1_TCIU1       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIU1)
#define IPR_MTU1_TCIU1       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIU1)
#define IEN_MTU1_TCIU1       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIU1)
#define VECT_MTU1_TCIU1      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU1_TCIU1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIA2)
#define IR_MTU2_TGIA2        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIA2)
#define DTCE_MTU2_TGIA2      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIA2)
#define IER_MTU2_TGIA2       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIA2)
#define IPR_MTU2_TGIA2       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIA2)
#define IEN_MTU2_TGIA2       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIA2)
#define VECT_MTU2_TGIA2      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIA2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIB2)
#define IR_MTU2_TGIB2        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIB2)
#define DTCE_MTU2_TGIB2      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIB2)
#define IER_MTU2_TGIB2       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIB2)
#define IPR_MTU2_TGIB2       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIB2)
#define IEN_MTU2_TGIB2       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIB2)
#define VECT_MTU2_TGIB2      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TGIB2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIV2)
#define IR_MTU2_TCIV2        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIV2)
#define DTCE_MTU2_TCIV2      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIV2)
#define IER_MTU2_TCIV2       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIV2)
#define IPR_MTU2_TCIV2       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIV2)
#define IEN_MTU2_TCIV2       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIV2)
#define VECT_MTU2_TCIV2      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIV2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIU2)
#define IR_MTU2_TCIU2        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIU2)
#define DTCE_MTU2_TCIU2      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIU2)
#define IER_MTU2_TCIU2       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIU2)
#define IPR_MTU2_TCIU2       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIU2)
#define IEN_MTU2_TCIU2       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIU2)
#define VECT_MTU2_TCIU2      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU2_TCIU2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIA3)
#define IR_MTU3_TGIA3        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIA3)
#define DTCE_MTU3_TGIA3      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIA3)
#define IER_MTU3_TGIA3       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIA3)
#define IPR_MTU3_TGIA3       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIA3)
#define IEN_MTU3_TGIA3       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIA3)
#define VECT_MTU3_TGIA3      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIA3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIB3)
#define IR_MTU3_TGIB3        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIB3)
#define DTCE_MTU3_TGIB3      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIB3)
#define IER_MTU3_TGIB3       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIB3)
#define IPR_MTU3_TGIB3       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIB3)
#define IEN_MTU3_TGIB3       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIB3)
#define VECT_MTU3_TGIB3      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIB3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIC3)
#define IR_MTU3_TGIC3        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIC3)
#define DTCE_MTU3_TGIC3      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIC3)
#define IER_MTU3_TGIC3       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIC3)
#define IPR_MTU3_TGIC3       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIC3)
#define IEN_MTU3_TGIC3       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIC3)
#define VECT_MTU3_TGIC3      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGIC3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGID3)
#define IR_MTU3_TGID3        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGID3)
#define DTCE_MTU3_TGID3      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGID3)
#define IER_MTU3_TGID3       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGID3)
#define IPR_MTU3_TGID3       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGID3)
#define IEN_MTU3_TGID3       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGID3)
#define VECT_MTU3_TGID3      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TGID3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TCIV3)
#define IR_MTU3_TCIV3        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TCIV3)
#define DTCE_MTU3_TCIV3      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TCIV3)
#define IER_MTU3_TCIV3       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TCIV3)
#define IPR_MTU3_TCIV3       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TCIV3)
#define IEN_MTU3_TCIV3       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU3_TCIV3)
#define VECT_MTU3_TCIV3      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU3_TCIV3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIA4)
#define IR_MTU4_TGIA4        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIA4)
#define DTCE_MTU4_TGIA4      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIA4)
#define IER_MTU4_TGIA4       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIA4)
#define IPR_MTU4_TGIA4       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIA4)
#define IEN_MTU4_TGIA4       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIA4)
#define VECT_MTU4_TGIA4      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIA4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIB4)
#define IR_MTU4_TGIB4        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIB4)
#define DTCE_MTU4_TGIB4      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIB4)
#define IER_MTU4_TGIB4       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIB4)
#define IPR_MTU4_TGIB4       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIB4)
#define IEN_MTU4_TGIB4       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIB4)
#define VECT_MTU4_TGIB4      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIB4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIC4)
#define IR_MTU4_TGIC4        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIC4)
#define DTCE_MTU4_TGIC4      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIC4)
#define IER_MTU4_TGIC4       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIC4)
#define IPR_MTU4_TGIC4       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIC4)
#define IEN_MTU4_TGIC4       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIC4)
#define VECT_MTU4_TGIC4      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGIC4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGID4)
#define IR_MTU4_TGID4        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGID4)
#define DTCE_MTU4_TGID4      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGID4)
#define IER_MTU4_TGID4       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGID4)
#define IPR_MTU4_TGID4       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGID4)
#define IEN_MTU4_TGID4       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGID4)
#define VECT_MTU4_TGID4      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TGID4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TCIV4)
#define IR_MTU4_TCIV4        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TCIV4)
#define DTCE_MTU4_TCIV4      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TCIV4)
#define IER_MTU4_TCIV4       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TCIV4)
#define IPR_MTU4_TCIV4       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TCIV4)
#define IEN_MTU4_TCIV4       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU4_TCIV4)
#define VECT_MTU4_TCIV4      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU4_TCIV4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIU5)
#define IR_MTU5_TGIU5        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIU5)
#define DTCE_MTU5_TGIU5      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIU5)
#define IER_MTU5_TGIU5       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIU5)
#define IPR_MTU5_TGIU5       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIU5)
#define IEN_MTU5_TGIU5       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIU5)
#define VECT_MTU5_TGIU5      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIU5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIV5)
#define IR_MTU5_TGIV5        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIV5)
#define DTCE_MTU5_TGIV5      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIV5)
#define IER_MTU5_TGIV5       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIV5)
#define IPR_MTU5_TGIV5       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIV5)
#define IEN_MTU5_TGIV5       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIV5)
#define VECT_MTU5_TGIV5      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIV5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIW5)
#define IR_MTU5_TGIW5        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIW5)
#define DTCE_MTU5_TGIW5      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIW5)
#define IER_MTU5_TGIW5       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIW5)
#define IPR_MTU5_TGIW5       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIW5)
#define IEN_MTU5_TGIW5       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIW5)
#define VECT_MTU5_TGIW5      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU5_TGIW5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIA6)
#define IR_MTU6_TGIA6        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIA6)
#define DTCE_MTU6_TGIA6      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIA6)
#define IER_MTU6_TGIA6       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIA6)
#define IPR_MTU6_TGIA6       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIA6)
#define IEN_MTU6_TGIA6       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIA6)
#define VECT_MTU6_TGIA6      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIA6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIB6)
#define IR_MTU6_TGIB6        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIB6)
#define DTCE_MTU6_TGIB6      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIB6)
#define IER_MTU6_TGIB6       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIB6)
#define IPR_MTU6_TGIB6       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIB6)
#define IEN_MTU6_TGIB6       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIB6)
#define VECT_MTU6_TGIB6      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIB6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIC6)
#define IR_MTU6_TGIC6        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIC6)
#define DTCE_MTU6_TGIC6      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIC6)
#define IER_MTU6_TGIC6       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIC6)
#define IPR_MTU6_TGIC6       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIC6)
#define IEN_MTU6_TGIC6       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIC6)
#define VECT_MTU6_TGIC6      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGIC6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGID6)
#define IR_MTU6_TGID6        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGID6)
#define DTCE_MTU6_TGID6      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGID6)
#define IER_MTU6_TGID6       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGID6)
#define IPR_MTU6_TGID6       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGID6)
#define IEN_MTU6_TGID6       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGID6)
#define VECT_MTU6_TGID6      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TGID6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TCIV6)
#define IR_MTU6_TCIV6        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TCIV6)
#define DTCE_MTU6_TCIV6      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TCIV6)
#define IER_MTU6_TCIV6       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TCIV6)
#define IPR_MTU6_TCIV6       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TCIV6)
#define IEN_MTU6_TCIV6       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU6_TCIV6)
#define VECT_MTU6_TCIV6      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU6_TCIV6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIA7)
#define IR_MTU7_TGIA7        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIA7)
#define DTCE_MTU7_TGIA7      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIA7)
#define IER_MTU7_TGIA7       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIA7)
#define IPR_MTU7_TGIA7       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIA7)
#define IEN_MTU7_TGIA7       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIA7)
#define VECT_MTU7_TGIA7      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIA7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIB7)
#define IR_MTU7_TGIB7        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIB7)
#define DTCE_MTU7_TGIB7      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIB7)
#define IER_MTU7_TGIB7       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIB7)
#define IPR_MTU7_TGIB7       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIB7)
#define IEN_MTU7_TGIB7       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIB7)
#define VECT_MTU7_TGIB7      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIB7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIC7)
#define IR_MTU7_TGIC7        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIC7)
#define DTCE_MTU7_TGIC7      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIC7)
#define IER_MTU7_TGIC7       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIC7)
#define IPR_MTU7_TGIC7       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIC7)
#define IEN_MTU7_TGIC7       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIC7)
#define VECT_MTU7_TGIC7      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGIC7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGID7)
#define IR_MTU7_TGID7        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGID7)
#define DTCE_MTU7_TGID7      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGID7)
#define IER_MTU7_TGID7       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGID7)
#define IPR_MTU7_TGID7       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGID7)
#define IEN_MTU7_TGID7       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGID7)
#define VECT_MTU7_TGID7      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TGID7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TCIV7)
#define IR_MTU7_TCIV7        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TCIV7)
#define DTCE_MTU7_TCIV7      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TCIV7)
#define IER_MTU7_TCIV7       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TCIV7)
#define IPR_MTU7_TCIV7       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TCIV7)
#define IEN_MTU7_TCIV7       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU7_TCIV7)
#define VECT_MTU7_TCIV7      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU7_TCIV7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIA9)
#define IR_MTU9_TGIA9        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIA9)
#define DTCE_MTU9_TGIA9      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIA9)
#define IER_MTU9_TGIA9       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIA9)
#define IPR_MTU9_TGIA9       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIA9)
#define IEN_MTU9_TGIA9       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIA9)
#define VECT_MTU9_TGIA9      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIA9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIB9)
#define IR_MTU9_TGIB9        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIB9)
#define DTCE_MTU9_TGIB9      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIB9)
#define IER_MTU9_TGIB9       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIB9)
#define IPR_MTU9_TGIB9       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIB9)
#define IEN_MTU9_TGIB9       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIB9)
#define VECT_MTU9_TGIB9      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIB9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIC9)
#define IR_MTU9_TGIC9        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIC9)
#define DTCE_MTU9_TGIC9      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIC9)
#define IER_MTU9_TGIC9       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIC9)
#define IPR_MTU9_TGIC9       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIC9)
#define IEN_MTU9_TGIC9       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIC9)
#define VECT_MTU9_TGIC9      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIC9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGID9)
#define IR_MTU9_TGID9        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGID9)
#define DTCE_MTU9_TGID9      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGID9)
#define IER_MTU9_TGID9       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGID9)
#define IPR_MTU9_TGID9       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGID9)
#define IEN_MTU9_TGID9       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGID9)
#define VECT_MTU9_TGID9      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGID9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TCIV9)
#define IR_MTU9_TCIV9        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TCIV9)
#define DTCE_MTU9_TCIV9      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TCIV9)
#define IER_MTU9_TCIV9       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TCIV9)
#define IPR_MTU9_TCIV9       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TCIV9)
#define IEN_MTU9_TCIV9       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TCIV9)
#define VECT_MTU9_TCIV9      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TCIV9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIE9)
#define IR_MTU9_TGIE9        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIE9)
#define DTCE_MTU9_TGIE9      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIE9)
#define IER_MTU9_TGIE9       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIE9)
#define IPR_MTU9_TGIE9       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIE9)
#define IEN_MTU9_TGIE9       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIE9)
#define VECT_MTU9_TGIE9      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIE9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIF9)
#define IR_MTU9_TGIF9        BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIF9)
#define DTCE_MTU9_TGIF9      BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIF9)
#define IER_MTU9_TGIF9       BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIF9)
#define IPR_MTU9_TGIF9       BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIF9)
#define IEN_MTU9_TGIF9       BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIF9)
#define VECT_MTU9_TGIF9      BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_MTU9_TGIF9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIA0)
#define IR_GPTW0_GTCIA0      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIA0)
#define DTCE_GPTW0_GTCIA0    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIA0)
#define IER_GPTW0_GTCIA0     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIA0)
#define IPR_GPTW0_GTCIA0     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIA0)
#define IEN_GPTW0_GTCIA0     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIA0)
#define VECT_GPTW0_GTCIA0    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIA0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIB0)
#define IR_GPTW0_GTCIB0      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIB0)
#define DTCE_GPTW0_GTCIB0    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIB0)
#define IER_GPTW0_GTCIB0     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIB0)
#define IPR_GPTW0_GTCIB0     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIB0)
#define IEN_GPTW0_GTCIB0     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIB0)
#define VECT_GPTW0_GTCIB0    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIB0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIC0)
#define IR_GPTW0_GTCIC0      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIC0)
#define DTCE_GPTW0_GTCIC0    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIC0)
#define IER_GPTW0_GTCIC0     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIC0)
#define IPR_GPTW0_GTCIC0     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIC0)
#define IEN_GPTW0_GTCIC0     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIC0)
#define VECT_GPTW0_GTCIC0    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIC0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCID0)
#define IR_GPTW0_GTCID0      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCID0)
#define DTCE_GPTW0_GTCID0    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCID0)
#define IER_GPTW0_GTCID0     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCID0)
#define IPR_GPTW0_GTCID0     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCID0)
#define IEN_GPTW0_GTCID0     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCID0)
#define VECT_GPTW0_GTCID0    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCID0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GDTE0)
#define IR_GPTW0_GDTE0       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GDTE0)
#define DTCE_GPTW0_GDTE0     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GDTE0)
#define IER_GPTW0_GDTE0      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GDTE0)
#define IPR_GPTW0_GDTE0      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GDTE0)
#define IEN_GPTW0_GDTE0      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GDTE0)
#define VECT_GPTW0_GDTE0     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GDTE0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIE0)
#define IR_GPTW0_GTCIE0      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIE0)
#define DTCE_GPTW0_GTCIE0    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIE0)
#define IER_GPTW0_GTCIE0     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIE0)
#define IPR_GPTW0_GTCIE0     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIE0)
#define IEN_GPTW0_GTCIE0     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIE0)
#define VECT_GPTW0_GTCIE0    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIE0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIF0)
#define IR_GPTW0_GTCIF0      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIF0)
#define DTCE_GPTW0_GTCIF0    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIF0)
#define IER_GPTW0_GTCIF0     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIF0)
#define IPR_GPTW0_GTCIF0     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIF0)
#define IEN_GPTW0_GTCIF0     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIF0)
#define VECT_GPTW0_GTCIF0    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIF0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIV0)
#define IR_GPTW0_GTCIV0      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIV0)
#define DTCE_GPTW0_GTCIV0    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIV0)
#define IER_GPTW0_GTCIV0     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIV0)
#define IPR_GPTW0_GTCIV0     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIV0)
#define IEN_GPTW0_GTCIV0     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIV0)
#define VECT_GPTW0_GTCIV0    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIV0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIU0)
#define IR_GPTW0_GTCIU0      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIU0)
#define DTCE_GPTW0_GTCIU0    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIU0)
#define IER_GPTW0_GTCIU0     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIU0)
#define IPR_GPTW0_GTCIU0     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIU0)
#define IEN_GPTW0_GTCIU0     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIU0)
#define VECT_GPTW0_GTCIU0    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW0_GTCIU0)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIA1)
#define IR_GPTW1_GTCIA1      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIA1)
#define DTCE_GPTW1_GTCIA1    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIA1)
#define IER_GPTW1_GTCIA1     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIA1)
#define IPR_GPTW1_GTCIA1     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIA1)
#define IEN_GPTW1_GTCIA1     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIA1)
#define VECT_GPTW1_GTCIA1    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIA1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIB1)
#define IR_GPTW1_GTCIB1      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIB1)
#define DTCE_GPTW1_GTCIB1    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIB1)
#define IER_GPTW1_GTCIB1     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIB1)
#define IPR_GPTW1_GTCIB1     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIB1)
#define IEN_GPTW1_GTCIB1     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIB1)
#define VECT_GPTW1_GTCIB1    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIB1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIC1)
#define IR_GPTW1_GTCIC1      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIC1)
#define DTCE_GPTW1_GTCIC1    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIC1)
#define IER_GPTW1_GTCIC1     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIC1)
#define IPR_GPTW1_GTCIC1     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIC1)
#define IEN_GPTW1_GTCIC1     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIC1)
#define VECT_GPTW1_GTCIC1    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIC1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCID1)
#define IR_GPTW1_GTCID1      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCID1)
#define DTCE_GPTW1_GTCID1    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCID1)
#define IER_GPTW1_GTCID1     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCID1)
#define IPR_GPTW1_GTCID1     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCID1)
#define IEN_GPTW1_GTCID1     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCID1)
#define VECT_GPTW1_GTCID1    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCID1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GDTE1)
#define IR_GPTW1_GDTE1       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GDTE1)
#define DTCE_GPTW1_GDTE1     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GDTE1)
#define IER_GPTW1_GDTE1      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GDTE1)
#define IPR_GPTW1_GDTE1      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GDTE1)
#define IEN_GPTW1_GDTE1      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GDTE1)
#define VECT_GPTW1_GDTE1     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GDTE1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIE1)
#define IR_GPTW1_GTCIE1      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIE1)
#define DTCE_GPTW1_GTCIE1    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIE1)
#define IER_GPTW1_GTCIE1     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIE1)
#define IPR_GPTW1_GTCIE1     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIE1)
#define IEN_GPTW1_GTCIE1     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIE1)
#define VECT_GPTW1_GTCIE1    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIE1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIF1)
#define IR_GPTW1_GTCIF1      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIF1)
#define DTCE_GPTW1_GTCIF1    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIF1)
#define IER_GPTW1_GTCIF1     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIF1)
#define IPR_GPTW1_GTCIF1     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIF1)
#define IEN_GPTW1_GTCIF1     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIF1)
#define VECT_GPTW1_GTCIF1    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIF1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIV1)
#define IR_GPTW1_GTCIV1      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIV1)
#define DTCE_GPTW1_GTCIV1    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIV1)
#define IER_GPTW1_GTCIV1     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIV1)
#define IPR_GPTW1_GTCIV1     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIV1)
#define IEN_GPTW1_GTCIV1     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIV1)
#define VECT_GPTW1_GTCIV1    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIV1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIU1)
#define IR_GPTW1_GTCIU1      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIU1)
#define DTCE_GPTW1_GTCIU1    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIU1)
#define IER_GPTW1_GTCIU1     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIU1)
#define IPR_GPTW1_GTCIU1     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIU1)
#define IEN_GPTW1_GTCIU1     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIU1)
#define VECT_GPTW1_GTCIU1    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW1_GTCIU1)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIA2)
#define IR_GPTW2_GTCIA2      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIA2)
#define DTCE_GPTW2_GTCIA2    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIA2)
#define IER_GPTW2_GTCIA2     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIA2)
#define IPR_GPTW2_GTCIA2     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIA2)
#define IEN_GPTW2_GTCIA2     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIA2)
#define VECT_GPTW2_GTCIA2    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIA2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIB2)
#define IR_GPTW2_GTCIB2      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIB2)
#define DTCE_GPTW2_GTCIB2    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIB2)
#define IER_GPTW2_GTCIB2     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIB2)
#define IPR_GPTW2_GTCIB2     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIB2)
#define IEN_GPTW2_GTCIB2     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIB2)
#define VECT_GPTW2_GTCIB2    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIB2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIC2)
#define IR_GPTW2_GTCIC2      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIC2)
#define DTCE_GPTW2_GTCIC2    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIC2)
#define IER_GPTW2_GTCIC2     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIC2)
#define IPR_GPTW2_GTCIC2     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIC2)
#define IEN_GPTW2_GTCIC2     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIC2)
#define VECT_GPTW2_GTCIC2    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIC2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCID2)
#define IR_GPTW2_GTCID2      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCID2)
#define DTCE_GPTW2_GTCID2    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCID2)
#define IER_GPTW2_GTCID2     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCID2)
#define IPR_GPTW2_GTCID2     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCID2)
#define IEN_GPTW2_GTCID2     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCID2)
#define VECT_GPTW2_GTCID2    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCID2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GDTE2)
#define IR_GPTW2_GDTE2       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GDTE2)
#define DTCE_GPTW2_GDTE2     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GDTE2)
#define IER_GPTW2_GDTE2      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GDTE2)
#define IPR_GPTW2_GDTE2      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GDTE2)
#define IEN_GPTW2_GDTE2      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GDTE2)
#define VECT_GPTW2_GDTE2     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GDTE2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIE2)
#define IR_GPTW2_GTCIE2      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIE2)
#define DTCE_GPTW2_GTCIE2    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIE2)
#define IER_GPTW2_GTCIE2     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIE2)
#define IPR_GPTW2_GTCIE2     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIE2)
#define IEN_GPTW2_GTCIE2     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIE2)
#define VECT_GPTW2_GTCIE2    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIE2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIF2)
#define IR_GPTW2_GTCIF2      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIF2)
#define DTCE_GPTW2_GTCIF2    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIF2)
#define IER_GPTW2_GTCIF2     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIF2)
#define IPR_GPTW2_GTCIF2     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIF2)
#define IEN_GPTW2_GTCIF2     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIF2)
#define VECT_GPTW2_GTCIF2    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIF2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIV2)
#define IR_GPTW2_GTCIV2      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIV2)
#define DTCE_GPTW2_GTCIV2    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIV2)
#define IER_GPTW2_GTCIV2     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIV2)
#define IPR_GPTW2_GTCIV2     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIV2)
#define IEN_GPTW2_GTCIV2     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIV2)
#define VECT_GPTW2_GTCIV2    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIV2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIU2)
#define IR_GPTW2_GTCIU2      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIU2)
#define DTCE_GPTW2_GTCIU2    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIU2)
#define IER_GPTW2_GTCIU2     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIU2)
#define IPR_GPTW2_GTCIU2     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIU2)
#define IEN_GPTW2_GTCIU2     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIU2)
#define VECT_GPTW2_GTCIU2    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW2_GTCIU2)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIA3)
#define IR_GPTW3_GTCIA3      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIA3)
#define DTCE_GPTW3_GTCIA3    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIA3)
#define IER_GPTW3_GTCIA3     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIA3)
#define IPR_GPTW3_GTCIA3     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIA3)
#define IEN_GPTW3_GTCIA3     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIA3)
#define VECT_GPTW3_GTCIA3    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIA3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIB3)
#define IR_GPTW3_GTCIB3      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIB3)
#define DTCE_GPTW3_GTCIB3    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIB3)
#define IER_GPTW3_GTCIB3     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIB3)
#define IPR_GPTW3_GTCIB3     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIB3)
#define IEN_GPTW3_GTCIB3     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIB3)
#define VECT_GPTW3_GTCIB3    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIB3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIC3)
#define IR_GPTW3_GTCIC3      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIC3)
#define DTCE_GPTW3_GTCIC3    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIC3)
#define IER_GPTW3_GTCIC3     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIC3)
#define IPR_GPTW3_GTCIC3     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIC3)
#define IEN_GPTW3_GTCIC3     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIC3)
#define VECT_GPTW3_GTCIC3    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIC3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCID3)
#define IR_GPTW3_GTCID3      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCID3)
#define DTCE_GPTW3_GTCID3    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCID3)
#define IER_GPTW3_GTCID3     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCID3)
#define IPR_GPTW3_GTCID3     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCID3)
#define IEN_GPTW3_GTCID3     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCID3)
#define VECT_GPTW3_GTCID3    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCID3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GDTE3)
#define IR_GPTW3_GDTE3       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GDTE3)
#define DTCE_GPTW3_GDTE3     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GDTE3)
#define IER_GPTW3_GDTE3      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GDTE3)
#define IPR_GPTW3_GDTE3      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GDTE3)
#define IEN_GPTW3_GDTE3      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GDTE3)
#define VECT_GPTW3_GDTE3     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GDTE3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIE3)
#define IR_GPTW3_GTCIE3      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIE3)
#define DTCE_GPTW3_GTCIE3    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIE3)
#define IER_GPTW3_GTCIE3     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIE3)
#define IPR_GPTW3_GTCIE3     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIE3)
#define IEN_GPTW3_GTCIE3     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIE3)
#define VECT_GPTW3_GTCIE3    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIE3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIF3)
#define IR_GPTW3_GTCIF3      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIF3)
#define DTCE_GPTW3_GTCIF3    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIF3)
#define IER_GPTW3_GTCIF3     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIF3)
#define IPR_GPTW3_GTCIF3     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIF3)
#define IEN_GPTW3_GTCIF3     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIF3)
#define VECT_GPTW3_GTCIF3    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIF3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIV3)
#define IR_GPTW3_GTCIV3      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIV3)
#define DTCE_GPTW3_GTCIV3    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIV3)
#define IER_GPTW3_GTCIV3     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIV3)
#define IPR_GPTW3_GTCIV3     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIV3)
#define IEN_GPTW3_GTCIV3     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIV3)
#define VECT_GPTW3_GTCIV3    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIV3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIU3)
#define IR_GPTW3_GTCIU3      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIU3)
#define DTCE_GPTW3_GTCIU3    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIU3)
#define IER_GPTW3_GTCIU3     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIU3)
#define IPR_GPTW3_GTCIU3     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIU3)
#define IEN_GPTW3_GTCIU3     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIU3)
#define VECT_GPTW3_GTCIU3    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW3_GTCIU3)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIA4)
#define IR_GPTW4_GTCIA4      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIA4)
#define DTCE_GPTW4_GTCIA4    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIA4)
#define IER_GPTW4_GTCIA4     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIA4)
#define IPR_GPTW4_GTCIA4     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIA4)
#define IEN_GPTW4_GTCIA4     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIA4)
#define VECT_GPTW4_GTCIA4    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIA4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIB4)
#define IR_GPTW4_GTCIB4      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIB4)
#define DTCE_GPTW4_GTCIB4    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIB4)
#define IER_GPTW4_GTCIB4     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIB4)
#define IPR_GPTW4_GTCIB4     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIB4)
#define IEN_GPTW4_GTCIB4     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIB4)
#define VECT_GPTW4_GTCIB4    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIB4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIC4)
#define IR_GPTW4_GTCIC4      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIC4)
#define DTCE_GPTW4_GTCIC4    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIC4)
#define IER_GPTW4_GTCIC4     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIC4)
#define IPR_GPTW4_GTCIC4     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIC4)
#define IEN_GPTW4_GTCIC4     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIC4)
#define VECT_GPTW4_GTCIC4    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIC4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCID4)
#define IR_GPTW4_GTCID4      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCID4)
#define DTCE_GPTW4_GTCID4    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCID4)
#define IER_GPTW4_GTCID4     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCID4)
#define IPR_GPTW4_GTCID4     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCID4)
#define IEN_GPTW4_GTCID4     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCID4)
#define VECT_GPTW4_GTCID4    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCID4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GDTE4)
#define IR_GPTW4_GDTE4       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GDTE4)
#define DTCE_GPTW4_GDTE4     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GDTE4)
#define IER_GPTW4_GDTE4      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GDTE4)
#define IPR_GPTW4_GDTE4      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GDTE4)
#define IEN_GPTW4_GDTE4      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GDTE4)
#define VECT_GPTW4_GDTE4     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GDTE4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIE4)
#define IR_GPTW4_GTCIE4      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIE4)
#define DTCE_GPTW4_GTCIE4    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIE4)
#define IER_GPTW4_GTCIE4     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIE4)
#define IPR_GPTW4_GTCIE4     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIE4)
#define IEN_GPTW4_GTCIE4     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIE4)
#define VECT_GPTW4_GTCIE4    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIE4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIF4)
#define IR_GPTW4_GTCIF4      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIF4)
#define DTCE_GPTW4_GTCIF4    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIF4)
#define IER_GPTW4_GTCIF4     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIF4)
#define IPR_GPTW4_GTCIF4     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIF4)
#define IEN_GPTW4_GTCIF4     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIF4)
#define VECT_GPTW4_GTCIF4    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIF4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIV4)
#define IR_GPTW4_GTCIV4      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIV4)
#define DTCE_GPTW4_GTCIV4    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIV4)
#define IER_GPTW4_GTCIV4     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIV4)
#define IPR_GPTW4_GTCIV4     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIV4)
#define IEN_GPTW4_GTCIV4     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIV4)
#define VECT_GPTW4_GTCIV4    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIV4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIU4)
#define IR_GPTW4_GTCIU4      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIU4)
#define DTCE_GPTW4_GTCIU4    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIU4)
#define IER_GPTW4_GTCIU4     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIU4)
#define IPR_GPTW4_GTCIU4     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIU4)
#define IEN_GPTW4_GTCIU4     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIU4)
#define VECT_GPTW4_GTCIU4    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW4_GTCIU4)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIA5)
#define IR_GPTW5_GTCIA5      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIA5)
#define DTCE_GPTW5_GTCIA5    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIA5)
#define IER_GPTW5_GTCIA5     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIA5)
#define IPR_GPTW5_GTCIA5     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIA5)
#define IEN_GPTW5_GTCIA5     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIA5)
#define VECT_GPTW5_GTCIA5    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIA5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIB5)
#define IR_GPTW5_GTCIB5      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIB5)
#define DTCE_GPTW5_GTCIB5    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIB5)
#define IER_GPTW5_GTCIB5     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIB5)
#define IPR_GPTW5_GTCIB5     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIB5)
#define IEN_GPTW5_GTCIB5     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIB5)
#define VECT_GPTW5_GTCIB5    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIB5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIC5)
#define IR_GPTW5_GTCIC5      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIC5)
#define DTCE_GPTW5_GTCIC5    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIC5)
#define IER_GPTW5_GTCIC5     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIC5)
#define IPR_GPTW5_GTCIC5     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIC5)
#define IEN_GPTW5_GTCIC5     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIC5)
#define VECT_GPTW5_GTCIC5    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIC5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCID5)
#define IR_GPTW5_GTCID5      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCID5)
#define DTCE_GPTW5_GTCID5    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCID5)
#define IER_GPTW5_GTCID5     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCID5)
#define IPR_GPTW5_GTCID5     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCID5)
#define IEN_GPTW5_GTCID5     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCID5)
#define VECT_GPTW5_GTCID5    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCID5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GDTE5)
#define IR_GPTW5_GDTE5       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GDTE5)
#define DTCE_GPTW5_GDTE5     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GDTE5)
#define IER_GPTW5_GDTE5      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GDTE5)
#define IPR_GPTW5_GDTE5      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GDTE5)
#define IEN_GPTW5_GDTE5      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GDTE5)
#define VECT_GPTW5_GDTE5     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GDTE5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIE5)
#define IR_GPTW5_GTCIE5      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIE5)
#define DTCE_GPTW5_GTCIE5    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIE5)
#define IER_GPTW5_GTCIE5     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIE5)
#define IPR_GPTW5_GTCIE5     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIE5)
#define IEN_GPTW5_GTCIE5     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIE5)
#define VECT_GPTW5_GTCIE5    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIE5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIF5)
#define IR_GPTW5_GTCIF5      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIF5)
#define DTCE_GPTW5_GTCIF5    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIF5)
#define IER_GPTW5_GTCIF5     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIF5)
#define IPR_GPTW5_GTCIF5     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIF5)
#define IEN_GPTW5_GTCIF5     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIF5)
#define VECT_GPTW5_GTCIF5    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIF5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIV5)
#define IR_GPTW5_GTCIV5      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIV5)
#define DTCE_GPTW5_GTCIV5    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIV5)
#define IER_GPTW5_GTCIV5     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIV5)
#define IPR_GPTW5_GTCIV5     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIV5)
#define IEN_GPTW5_GTCIV5     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIV5)
#define VECT_GPTW5_GTCIV5    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIV5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIU5)
#define IR_GPTW5_GTCIU5      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIU5)
#define DTCE_GPTW5_GTCIU5    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIU5)
#define IER_GPTW5_GTCIU5     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIU5)
#define IPR_GPTW5_GTCIU5     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIU5)
#define IEN_GPTW5_GTCIU5     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIU5)
#define VECT_GPTW5_GTCIU5    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW5_GTCIU5)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIA6)
#define IR_GPTW6_GTCIA6      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIA6)
#define DTCE_GPTW6_GTCIA6    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIA6)
#define IER_GPTW6_GTCIA6     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIA6)
#define IPR_GPTW6_GTCIA6     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIA6)
#define IEN_GPTW6_GTCIA6     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIA6)
#define VECT_GPTW6_GTCIA6    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIA6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIB6)
#define IR_GPTW6_GTCIB6      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIB6)
#define DTCE_GPTW6_GTCIB6    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIB6)
#define IER_GPTW6_GTCIB6     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIB6)
#define IPR_GPTW6_GTCIB6     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIB6)
#define IEN_GPTW6_GTCIB6     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIB6)
#define VECT_GPTW6_GTCIB6    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIB6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIC6)
#define IR_GPTW6_GTCIC6      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIC6)
#define DTCE_GPTW6_GTCIC6    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIC6)
#define IER_GPTW6_GTCIC6     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIC6)
#define IPR_GPTW6_GTCIC6     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIC6)
#define IEN_GPTW6_GTCIC6     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIC6)
#define VECT_GPTW6_GTCIC6    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIC6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCID6)
#define IR_GPTW6_GTCID6      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCID6)
#define DTCE_GPTW6_GTCID6    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCID6)
#define IER_GPTW6_GTCID6     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCID6)
#define IPR_GPTW6_GTCID6     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCID6)
#define IEN_GPTW6_GTCID6     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCID6)
#define VECT_GPTW6_GTCID6    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCID6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GDTE6)
#define IR_GPTW6_GDTE6       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GDTE6)
#define DTCE_GPTW6_GDTE6     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GDTE6)
#define IER_GPTW6_GDTE6      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GDTE6)
#define IPR_GPTW6_GDTE6      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GDTE6)
#define IEN_GPTW6_GDTE6      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GDTE6)
#define VECT_GPTW6_GDTE6     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GDTE6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIE6)
#define IR_GPTW6_GTCIE6      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIE6)
#define DTCE_GPTW6_GTCIE6    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIE6)
#define IER_GPTW6_GTCIE6     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIE6)
#define IPR_GPTW6_GTCIE6     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIE6)
#define IEN_GPTW6_GTCIE6     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIE6)
#define VECT_GPTW6_GTCIE6    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIE6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIF6)
#define IR_GPTW6_GTCIF6      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIF6)
#define DTCE_GPTW6_GTCIF6    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIF6)
#define IER_GPTW6_GTCIF6     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIF6)
#define IPR_GPTW6_GTCIF6     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIF6)
#define IEN_GPTW6_GTCIF6     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIF6)
#define VECT_GPTW6_GTCIF6    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIF6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIV6)
#define IR_GPTW6_GTCIV6      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIV6)
#define DTCE_GPTW6_GTCIV6    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIV6)
#define IER_GPTW6_GTCIV6     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIV6)
#define IPR_GPTW6_GTCIV6     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIV6)
#define IEN_GPTW6_GTCIV6     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIV6)
#define VECT_GPTW6_GTCIV6    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIV6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIU6)
#define IR_GPTW6_GTCIU6      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIU6)
#define DTCE_GPTW6_GTCIU6    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIU6)
#define IER_GPTW6_GTCIU6     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIU6)
#define IPR_GPTW6_GTCIU6     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIU6)
#define IEN_GPTW6_GTCIU6     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIU6)
#define VECT_GPTW6_GTCIU6    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW6_GTCIU6)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIA7)
#define IR_GPTW7_GTCIA7      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIA7)
#define DTCE_GPTW7_GTCIA7    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIA7)
#define IER_GPTW7_GTCIA7     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIA7)
#define IPR_GPTW7_GTCIA7     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIA7)
#define IEN_GPTW7_GTCIA7     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIA7)
#define VECT_GPTW7_GTCIA7    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIA7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIB7)
#define IR_GPTW7_GTCIB7      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIB7)
#define DTCE_GPTW7_GTCIB7    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIB7)
#define IER_GPTW7_GTCIB7     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIB7)
#define IPR_GPTW7_GTCIB7     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIB7)
#define IEN_GPTW7_GTCIB7     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIB7)
#define VECT_GPTW7_GTCIB7    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIB7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIC7)
#define IR_GPTW7_GTCIC7      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIC7)
#define DTCE_GPTW7_GTCIC7    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIC7)
#define IER_GPTW7_GTCIC7     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIC7)
#define IPR_GPTW7_GTCIC7     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIC7)
#define IEN_GPTW7_GTCIC7     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIC7)
#define VECT_GPTW7_GTCIC7    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIC7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCID7)
#define IR_GPTW7_GTCID7      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCID7)
#define DTCE_GPTW7_GTCID7    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCID7)
#define IER_GPTW7_GTCID7     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCID7)
#define IPR_GPTW7_GTCID7     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCID7)
#define IEN_GPTW7_GTCID7     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCID7)
#define VECT_GPTW7_GTCID7    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCID7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GDTE7)
#define IR_GPTW7_GDTE7       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GDTE7)
#define DTCE_GPTW7_GDTE7     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GDTE7)
#define IER_GPTW7_GDTE7      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GDTE7)
#define IPR_GPTW7_GDTE7      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GDTE7)
#define IEN_GPTW7_GDTE7      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GDTE7)
#define VECT_GPTW7_GDTE7     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GDTE7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIE7)
#define IR_GPTW7_GTCIE7      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIE7)
#define DTCE_GPTW7_GTCIE7    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIE7)
#define IER_GPTW7_GTCIE7     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIE7)
#define IPR_GPTW7_GTCIE7     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIE7)
#define IEN_GPTW7_GTCIE7     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIE7)
#define VECT_GPTW7_GTCIE7    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIE7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIF7)
#define IR_GPTW7_GTCIF7      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIF7)
#define DTCE_GPTW7_GTCIF7    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIF7)
#define IER_GPTW7_GTCIF7     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIF7)
#define IPR_GPTW7_GTCIF7     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIF7)
#define IEN_GPTW7_GTCIF7     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIF7)
#define VECT_GPTW7_GTCIF7    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIF7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIV7)
#define IR_GPTW7_GTCIV7      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIV7)
#define DTCE_GPTW7_GTCIV7    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIV7)
#define IER_GPTW7_GTCIV7     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIV7)
#define IPR_GPTW7_GTCIV7     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIV7)
#define IEN_GPTW7_GTCIV7     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIV7)
#define VECT_GPTW7_GTCIV7    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIV7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIU7)
#define IR_GPTW7_GTCIU7      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIU7)
#define DTCE_GPTW7_GTCIU7    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIU7)
#define IER_GPTW7_GTCIU7     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIU7)
#define IPR_GPTW7_GTCIU7     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIU7)
#define IEN_GPTW7_GTCIU7     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIU7)
#define VECT_GPTW7_GTCIU7    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW7_GTCIU7)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIA8)
#define IR_GPTW8_GTCIA8      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIA8)
#define DTCE_GPTW8_GTCIA8    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIA8)
#define IER_GPTW8_GTCIA8     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIA8)
#define IPR_GPTW8_GTCIA8     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIA8)
#define IEN_GPTW8_GTCIA8     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIA8)
#define VECT_GPTW8_GTCIA8    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIA8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIB8)
#define IR_GPTW8_GTCIB8      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIB8)
#define DTCE_GPTW8_GTCIB8    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIB8)
#define IER_GPTW8_GTCIB8     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIB8)
#define IPR_GPTW8_GTCIB8     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIB8)
#define IEN_GPTW8_GTCIB8     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIB8)
#define VECT_GPTW8_GTCIB8    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIB8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIC8)
#define IR_GPTW8_GTCIC8      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIC8)
#define DTCE_GPTW8_GTCIC8    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIC8)
#define IER_GPTW8_GTCIC8     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIC8)
#define IPR_GPTW8_GTCIC8     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIC8)
#define IEN_GPTW8_GTCIC8     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIC8)
#define VECT_GPTW8_GTCIC8    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIC8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCID8)
#define IR_GPTW8_GTCID8      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCID8)
#define DTCE_GPTW8_GTCID8    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCID8)
#define IER_GPTW8_GTCID8     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCID8)
#define IPR_GPTW8_GTCID8     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCID8)
#define IEN_GPTW8_GTCID8     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCID8)
#define VECT_GPTW8_GTCID8    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCID8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GDTE8)
#define IR_GPTW8_GDTE8       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GDTE8)
#define DTCE_GPTW8_GDTE8     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GDTE8)
#define IER_GPTW8_GDTE8      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GDTE8)
#define IPR_GPTW8_GDTE8      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GDTE8)
#define IEN_GPTW8_GDTE8      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GDTE8)
#define VECT_GPTW8_GDTE8     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GDTE8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIE8)
#define IR_GPTW8_GTCIE8      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIE8)
#define DTCE_GPTW8_GTCIE8    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIE8)
#define IER_GPTW8_GTCIE8     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIE8)
#define IPR_GPTW8_GTCIE8     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIE8)
#define IEN_GPTW8_GTCIE8     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIE8)
#define VECT_GPTW8_GTCIE8    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIE8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIF8)
#define IR_GPTW8_GTCIF8      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIF8)
#define DTCE_GPTW8_GTCIF8    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIF8)
#define IER_GPTW8_GTCIF8     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIF8)
#define IPR_GPTW8_GTCIF8     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIF8)
#define IEN_GPTW8_GTCIF8     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIF8)
#define VECT_GPTW8_GTCIF8    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIF8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIV8)
#define IR_GPTW8_GTCIV8      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIV8)
#define DTCE_GPTW8_GTCIV8    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIV8)
#define IER_GPTW8_GTCIV8     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIV8)
#define IPR_GPTW8_GTCIV8     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIV8)
#define IEN_GPTW8_GTCIV8     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIV8)
#define VECT_GPTW8_GTCIV8    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIV8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIU8)
#define IR_GPTW8_GTCIU8      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIU8)
#define DTCE_GPTW8_GTCIU8    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIU8)
#define IER_GPTW8_GTCIU8     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIU8)
#define IPR_GPTW8_GTCIU8     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIU8)
#define IEN_GPTW8_GTCIU8     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIU8)
#define VECT_GPTW8_GTCIU8    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW8_GTCIU8)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIA9)
#define IR_GPTW9_GTCIA9      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIA9)
#define DTCE_GPTW9_GTCIA9    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIA9)
#define IER_GPTW9_GTCIA9     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIA9)
#define IPR_GPTW9_GTCIA9     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIA9)
#define IEN_GPTW9_GTCIA9     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIA9)
#define VECT_GPTW9_GTCIA9    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIA9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIB9)
#define IR_GPTW9_GTCIB9      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIB9)
#define DTCE_GPTW9_GTCIB9    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIB9)
#define IER_GPTW9_GTCIB9     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIB9)
#define IPR_GPTW9_GTCIB9     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIB9)
#define IEN_GPTW9_GTCIB9     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIB9)
#define VECT_GPTW9_GTCIB9    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIB9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIC9)
#define IR_GPTW9_GTCIC9      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIC9)
#define DTCE_GPTW9_GTCIC9    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIC9)
#define IER_GPTW9_GTCIC9     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIC9)
#define IPR_GPTW9_GTCIC9     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIC9)
#define IEN_GPTW9_GTCIC9     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIC9)
#define VECT_GPTW9_GTCIC9    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIC9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCID9)
#define IR_GPTW9_GTCID9      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCID9)
#define DTCE_GPTW9_GTCID9    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCID9)
#define IER_GPTW9_GTCID9     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCID9)
#define IPR_GPTW9_GTCID9     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCID9)
#define IEN_GPTW9_GTCID9     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCID9)
#define VECT_GPTW9_GTCID9    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCID9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GDTE9)
#define IR_GPTW9_GDTE9       BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GDTE9)
#define DTCE_GPTW9_GDTE9     BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GDTE9)
#define IER_GPTW9_GDTE9      BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GDTE9)
#define IPR_GPTW9_GDTE9      BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GDTE9)
#define IEN_GPTW9_GDTE9      BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GDTE9)
#define VECT_GPTW9_GDTE9     BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GDTE9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIE9)
#define IR_GPTW9_GTCIE9      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIE9)
#define DTCE_GPTW9_GTCIE9    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIE9)
#define IER_GPTW9_GTCIE9     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIE9)
#define IPR_GPTW9_GTCIE9     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIE9)
#define IEN_GPTW9_GTCIE9     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIE9)
#define VECT_GPTW9_GTCIE9    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIE9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIF9)
#define IR_GPTW9_GTCIF9      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIF9)
#define DTCE_GPTW9_GTCIF9    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIF9)
#define IER_GPTW9_GTCIF9     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIF9)
#define IPR_GPTW9_GTCIF9     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIF9)
#define IEN_GPTW9_GTCIF9     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIF9)
#define VECT_GPTW9_GTCIF9    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIF9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIV9)
#define IR_GPTW9_GTCIV9      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIV9)
#define DTCE_GPTW9_GTCIV9    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIV9)
#define IER_GPTW9_GTCIV9     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIV9)
#define IPR_GPTW9_GTCIV9     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIV9)
#define IEN_GPTW9_GTCIV9     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIV9)
#define VECT_GPTW9_GTCIV9    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIV9)
#endif

#if BSP_PRV_VALID_MAP_INT(A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIU9)
#define IR_GPTW9_GTCIU9      BSP_PRV_IR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIU9)
#define DTCE_GPTW9_GTCIU9    BSP_PRV_DTCE(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIU9)
#define IER_GPTW9_GTCIU9     BSP_PRIV_CALC_IER_REG(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIU9)
#define IPR_GPTW9_GTCIU9     BSP_PRV_IPR(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIU9)
#define IEN_GPTW9_GTCIU9     BSP_PRV_IEN(BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIU9)
#define VECT_GPTW9_GTCIU9    BSP_PRV_VECT(BSP_PRV_A, BSP_MAPPED_INT_CFG_A_VECT_GPTW9_GTCIU9)
#endif

/***********************************************************************************************************************
Typedef definitions
***********************************************************************************************************************/

/***********************************************************************************************************************
Exported global variables
***********************************************************************************************************************/

/***********************************************************************************************************************
Exported global functions (to be accessed by other files)
***********************************************************************************************************************/
void bsp_mapped_interrupt_open(void); //r_bsp internal function. DO NOT CALL.

#endif /* MCU_MAPPED_INTERRUPTS_H */

