set(
    AFR_MANIFEST_SUPPORTED_BOARDS
    ""
    CACHE INTERNAL "Supported boards list."
)

set(AFR_MANIFEST_BOARD_DIR "boards")
set(AFR_MANIFEST_BOARD_DIR_cypress43 "boards/CYW943907AEVAL1F")
set(AFR_MANIFEST_BOARD_DIR_cypress54 "boards/CYW954907AEVAL1F")
