#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

$(error Make build system is not supported, please use CMake build system. For more details please refer to getting started guide)


