include("${CMAKE_CURRENT_LIST_DIR}/afr_utils.cmake")
set(AFR_VENDORS_DIR "${AFR_ROOT_DIR}/vendors")

afr_get_vendors(vendors)

foreach(vendor IN LISTS vendors)
    message("- name: ${vendor}")
    message("  path: vendors/${vendor}")
    message("  boards:")
    afr_get_vendor_boards("${vendor}" boards)
    foreach(board IN LISTS boards)
        message("    - name: ${board}")
        include("${AFR_VENDORS_DIR}/${vendor}/manifest.cmake")
        if(DEFINED AFR_MANIFEST_BOARD_DIR_${board})
            message("      path: ${AFR_MANIFEST_BOARD_DIR_${board}}")
        else()
            message("      path: ${AFR_MANIFEST_BOARD_DIR}/${board}")
        endif()
    endforeach()
endforeach()
