/*
 * Generated by MTK Easy PinMux Tool Version 1.0.7 for 7687. Copyright MediaTek Inc. (C) 2015.
 * Thu Oct 27 14:22:18 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/
#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H


#endif /* _EPT_EINT_DRV_H */


