#!/usr/bin/env python

import os
import subprocess



makefiles = [
    'Makefile-CheckOptions',
    'Makefile-CheckOptionsOuter',
    'Makefile-CheckOptionsInner',
    'Makefile-ProcessDHCPReplies',
    'Makefile-ParseDNSReply',
    'Makefile-ReadNameField',
    'Makefile-SkipNameField'
]

def run_makefile(file):
    print file

    cmd = ['make', '-f', file, 'veryclean']
    #print ' '.join(cmd)
    subprocess.check_output(cmd)

    cmd = ['make', '-f', file, 'cbmc']
    #print ' '.join(cmd)
    subprocess.check_output(cmd)
    with open('cbmc.txt') as fh:
        for line in fh:
            if line.startswith('**') and 'iteration' in line:
                print line.strip()

    cmd = ['make', '-f', file, 'report']
    #print ' '.join(cmd)
    subprocess.check_output(cmd)
    with open('html/index.html') as fh:
        for line in fh:
            if 'statically-reachable' in line:
                print line.strip()

    cmd = ['make', '-f', file, 'veryclean']
    #print ' '.join(cmd)
    subprocess.check_output(cmd)

    print

if __name__ == "__main__":
    for file in makefiles:
        run_makefile(file)
